// Generated by https://quicktype.io

export interface UserType {
    id: number;
    branch_id: null;
    name: string;
    email: string;
    email_verified_at: null;
    phone: string;
    address: string;
    image: null;
    role: string;
    created_at: null;
    updated_at: null;
}
